Add primes algorithm for go
bbc2/lang-bench pull request #8
Opened 2018-11-02 20:49 UTC by Stratus51

2018-11-03 21:31 UTC, bbc2 requested changes

2018-11-03 21:31 UTC, bbc2 commented on primes/go/Dockerfile
> +FROM golang:${VERSION}${DISTRIBUTION}
```suggestion
FROM golang:${VERSION}-${DISTRIBUTION}
```

2018-11-03 21:31 UTC, bbc2 commented on primes/go/Dockerfile
> +ENTRYPOINT ./go
```suggestion
ENTRYPOINT ./app
```

2018-11-03 22:04 UTC, Stratus51 commented on primes/go/Dockerfile
> +FROM golang:${VERSION}${DISTRIBUTION}
Fixed

2018-11-03 22:04 UTC, Stratus51 commented on primes/go/Dockerfile
> +ENTRYPOINT ./go
Fixed with proper build executable name specification (-o build option)

2018-11-04 07:32 UTC, bbc2 approved these changes

2018-11-04 07:32 UTC, merged